### ISSUE TITLE
tag validation for release branch workflow

### ISSUE THREAD

**Issue by alisabzevari** [inikulin/publish-please#51]
We are using this nice library in one of our team's libs. Our release workflow is as follows:
* When we want to release the next version, we create another branch called a release branch
* Then we run `npm version ...` command to increase the version
* Then we create another PR (called release PR) with the changelog
* After reviewing this PR and merging it to master we run the publish command

The problem is that, at this point, there is another 'merge to master' commit. So our tagged commit is one commit behind the last one. So the git tag validation does not work and we had to disable it.

Is there any workaround for this problem?

**Comment by inikulin** [comment]
⚠️LOOKING FOR MAINTAINERS ⚠️ Unfortunately I don't have enough time and interest in supporting this project anymore. If someone would like to step up as a maintainer for this project, please, drop a mail to ifaaan@gmail.com

**Comment by hdorgeval** [comment]
Hi @alisabzevari, Thanks for using publish-please. I think your problem is unsolvable since it means rewriting the history in order to move the tag on top of the commits history. You should create a new tag and then run publish-please.

Maybe you are looking for a new feature in publish-please like "automatically create a tag on the last commit" before publishing. Feel free to add this nice-to-have feature in [Vote for the next-to-have feature](https://github.com/inikulin/publish-please/issues/63)
